name: one_one
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  socket_io_client: ^3.1.2
  permission_handler: ^12.0.1
  flutter_webrtc: ^1.1.0
  shared_preferences: ^2.0.15
  flutter_foreground_task: ^9.1.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  image_picker: ^1.0.7
  image_cropper: ^11.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.2.16
  dio: ^5.9.0
  talker: ^5.0.0
  talker_dio_logger: ^5.0.0
  get_it: ^8.2.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter_native_splash:
  color: "#FFFF01"  # Background color
  image: assets/icon/logo.png  # Your logo image
  color_dark: "#FFFF01"  # Background color for dark mode
  android: true
  ios: true
  web: false

  android_12:
    color: "FFFF00"
    image: assets/icon/logo.png 

flutter:
  uses-material-design: true
  assets:
    - "assets/icon/logo.png"
    - "assets/icon/google.png"