// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPDMh6yffgIkx2WcIoMjHrfP1-RJ8lKwY',
    appId: '1:615995801871:android:4b4d694430ed92e16a3e7a',
    messagingSenderId: '615995801871',
    projectId: 'one-one-40e5d',
    storageBucket: 'one-one-40e5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9bfGZbJ7kgWkexRZKgoCkn3aewEnSDaM',
    appId: '1:615995801871:ios:86c575698d8f5f7d6a3e7a',
    messagingSenderId: '615995801871',
    projectId: 'one-one-40e5d',
    storageBucket: 'one-one-40e5d.firebasestorage.app',
    iosBundleId: 'com.example.tenTen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9bfGZbJ7kgWkexRZKgoCkn3aewEnSDaM',
    appId: '1:615995801871:ios:86c575698d8f5f7d6a3e7a',
    messagingSenderId: '615995801871',
    projectId: 'one-one-40e5d',
    storageBucket: 'one-one-40e5d.firebasestorage.app',
    iosBundleId: 'com.example.tenTen',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCic9YRbthQdRr0el7L7gwlz6NIB3o8eso',
    appId: '1:615995801871:web:dfb107005933d7fc6a3e7a',
    messagingSenderId: '615995801871',
    projectId: 'one-one-40e5d',
    authDomain: 'one-one-40e5d.firebaseapp.com',
    storageBucket: 'one-one-40e5d.firebasestorage.app',
    measurementId: 'G-DM49HV223P',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCic9YRbthQdRr0el7L7gwlz6NIB3o8eso',
    appId: '1:615995801871:web:84a113272be3ecef6a3e7a',
    messagingSenderId: '615995801871',
    projectId: 'one-one-40e5d',
    authDomain: 'one-one-40e5d.firebaseapp.com',
    storageBucket: 'one-one-40e5d.firebasestorage.app',
    measurementId: 'G-LKX9NQH6VV',
  );

}